[package]
name = "hashcards"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
csv = "1"
serde = { version = "1", features = ["derive"] }
uuid = { version = "1", features = ["v4"] }

[dev-dependencies]
tempfile = "3"
